const SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL";
const SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_PUBLIC_KEY";

const EVIDENCE_BUCKET = "evidence";
const MENTOR_CODE = "ADMIN_ONLY_NOT_USED_IN_PUBLIC_REGISTER";
